name: Post welcome comment

on:
  pull_request:
    types: [opened]
    
permissions:
  pull-requests: write 
  
jobs:
  welcome-job:
    runs-on: ubuntu-latest    
    steps:
      - name: First interaction
        run: gh pr comment 42 --body "Thanks for the update! Looks good."
    env:
      GIT_HUB_TOKEN: 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
      PR_URL: https://github.com/anjana5769/skills-hello-github-actions/pull/7

